### PR TITLE
Create popup for Email This Building message

### LINKED ISSUE #126: Add "Email This Building Button" To Building Details
We don't have the contact info for buildings, but we should create a modal that gives user's a filled out template email with the building's name and maybe some stats. Here's a V1 mockup from [my Figma](https://www.figma.com/design/rJQiz1waySWCRN9NdGtjtg/Electrify-Chicago?node-id=303-65&node-type=FRAME&t=zjpLfNePSroNp6yw-0)

Email Modal

**Make sure to think about accessibility, esp. trapping focus in the modal**, and see the [<dialog> element (MDN)](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog)

### PR DESCRIPTION
**Pull request by wangbertha**
# Description

- Create popup component for Email This Building message in BuildingDetails.vue page to address #126 
- No dependencies added

Resolves #126

# Testing Instructions

- Open/close Popup
- "Copy Text" button functionality
- Styling in wide-screen, narrow-screen, mobile, with and without Building image

# Checklist:

- [X] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by wangbertha** [comment]
@vkoves Functionality and styling since last night's meeting are now pushed!

**Comment by vkoves** [comment]
@wangbertha - this looks awesome! I made a few bits of fixes and cleanup so we can get this shipped, but I wanted to walk through a few so it makes sense:

### Accessibilty

**I moved to using a native HTML `<dialog>` (see [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog))** - the native <dialog> is new, and better for accessibility - it traps focus (so you can only tab in the modal, and can't tab the background when it's open) making it easier for keyboard users to interact with the modal. Try before and after to see what I mean!

**Dropped excess `alt` text** - the images in the modal are decorative, as in they don't communicate something in and of themselves, but are supplementary (e.g. an email icon in a button labelled "Email"). Having the alt text would create redundant content for screen readers (e.g. "Image email Email button" to describe a button with an image and text). If we _just_ had the icon, we'd 100% want to make sure we have appropriate alt text.


### Code 

**Moved Email Modal To Its Own Component** - the `BuildingDetails` file is already huge, so we want to avoid adding code to it as much as possible, so I split the email modal into a separate component file with it's own HTML and CSS, so the building details page just has to render `<email-building-modal>`.

**Moved To Vue Refs** - I think you had this setup (or were trying to) earlier, but I wasn't familiar with Vue refs, so I learned a bit more about them and pivoted to using that instead of `document.getElementById`, which is a more Vue way of doing it.

### Functionality

**Updated Styles** - I noticed a few widths and font sizes didn't quite match the mocks, so I just tuned those to get it looking just right.

**Added "Copied!" Notice** - I think this also falls under accessibility, but it's confusing when you can't tell an action has happened, so I added a simple animated text notice for when the user copies the subject or body, making it clear it's happened.

Here's a look with those changes:

Screenshot from 2024-12-06 21-26-00

**Review by vkoves — APPROVED** [review]
Great work on this! I made a few tweaks (see my comment) to save some back-and-forth, but if you have any questions or disagreement on those, let me know. Going to get this shipped so it'll be out there in the world 🎉

**Comment by wangbertha** [comment]
Thank you for your review and final changes! I'm excited to see the popup, now on the site! 🎉

**Pull request merged**
