### PR TITLE
Add Some Municipal Property Owners & Buildings (CPS, CHA & City of Chicago)

### LINKED ISSUE #12: Add Municipal Property Owners (City of Chicago, CHA, CPS, etc.)
Let's look up city of Chicago buildings, including police, fire, public housing, etc. Then we can add the property owners into the `buildings-custom-info.constant.vue`, where you have to:

1. Configure a new owner (look at say, Northwestern) with logos a key you'll use to tag buildings, and a name
2. Tag specific buildings with the new owner by their ID (shown at the top of a building's details page after "Chicago Building ID")

**This PR may be a helpful guide: PR #8**

### PR DESCRIPTION
**Pull request by SuragNuthulapaty**
# Description

Adds CPS, CHA, and City of Chicago property owners
Tags properties that belong to CPS, CHA, and City of Chicago with their respective property owners.

Fixes #12 

# Testing Instructions

As I can't run the project on my end, I am using neflify to check

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by SuragNuthulapaty** [comment]
@vkoves Additionally, I have not pushed the data set I used for city of Chicago or the scripts I used to process the main set for all 3 property owners. Should I commit those as well?
There are also some more things to do. I have not updated each of the 3 new property owners with correct logos. Also, CHA buildings might not be exhaustive but it is a start.

**Comment by SuragNuthulapaty** [comment]
image
Case in point for unchanged logo. This is a CHA property that shows the Northwestern Logo. I did not know what sort of constraints you had on these images so I did not add any

**Comment by vkoves** [comment]
@SuragNuthulapaty - just taking a quick starting peek, but what's your data source on the city buildings? Gallery 37 and MSI are definitely privately owned.

Screenshot from 2024-01-10 17-36-28

I'd make sure we're quite conservative with these - I'd rather have only five buildings tagged but know they are right than to falsely accuse a building of being owned by someone it isn't.

**Comment by SuragNuthulapaty** [comment]
Downloaded from this link, I have the dataset on my local computer and can push it up.
https://www.chicago.gov/city/en/depts/dcd/supp_info/city-owned_land_inventory.html

Also, for MSI specifically, the data set from the city says its owned by city, which is concerning
image

**Comment by SuragNuthulapaty** [comment]
image

similar story for Gallery 37, I'll look into finding a more accurate data source

**Comment by vkoves** [comment]
I wonder if the _land_ is owned by the city and somehow the building is leasing it from them? But we want to know about city owned buildings

**Comment by vkoves** [comment]
Also @SuragNuthulapaty for the logos I think a 1000px wide transparent PNG is perfect, but if you add anything I can help you edit it if needed!

**Comment by SuragNuthulapaty** [comment]
@vkoves just pushed up the csv I am using, looking at it we might be able to use the ```Managing Organization``` column to determine if the city actually owns the building. 

I'll also push up the scripts I am using if you want to take a look at it, along with some logos

**Comment by SuragNuthulapaty** [comment]
@vkoves just pushed up a few more logos, along with the updated ```bulding-custom-info.constant.vue```. I believe the only thing left to do is scan through the tagged buildings to ensure they are tagged properly. 

Also, not sure if I'll be able to make any more meetings for a while, so this is where ill leave this issue off from.

**Comment by vkoves** [comment]
1. Optimize `find_city_buildings` to use a map of address to building IDs, so you're not looping through all benchmark buildings for each city owned building. Make sure to skip buildings that aren't managed by AIS earlier.
2. Move these scripts into a `building-owner-helpers` directory to keep them isolated from main data parsing

**Comment by vkoves** [comment]
Looks good to me after our last meeting and reading the code, good work and thanks for tackling this!

**Review by vkoves — APPROVED** [review]

**Pull request merged**
