### PR TITLE
add docker-entrypoint

### PR DESCRIPTION
**Pull request by derekeder**
# Description

* Adds a `docker-entrypoint.sh` script for running docker commands without shelling into the server. With this, we can run commands like `docker-compose run --rm electrify-chicago bash run_all.sh`
* Updates the Readme with instructions to run commands

Note that you will likely need to run `docker-compose build` before this will work for you.

# Testing Instructions

* run `docker-compose build` to rebuild container
* run `docker-compose run --rm electrify-chicago bash run_all.sh` and confirm it executes as expected

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by derekeder** [comment]
it looks like tests are failing for reasons unrelated to these changes:

```
 -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED tests/data/scripts/unit/test_clean_all_years.py::test_str_values_remain_the_same_as_origin - AssertionError: assert '41.83292416819927' == '41.832924168'
  - 41.832924168
  + 41.83292416819927
  ?             +++++
=================== 1 failed, 11 passed, 1 warning in 0.78s ====================
Error: Process completed with exit code 1.
```

**Review by gaylem — APPROVED** [review]
Works for me! I also ran the other commands and they worked as expected:

- `docker-compose run --rm electrify-chicago yarn lint-fix`
- `docker-compose run --rm electrify-chicago bash create_test_data.sh`
- `docker-compose run --rm electrify-chicago python -m pytest`

I'll update the README as well

**Comment by gaylem** [comment]
Here's the PR for the README changes: https://github.com/vkoves/electrify-chicago/pull/91

**Comment by derekeder** [comment]
@gaylem thx! I updated the readme already in this PR. Does it look right to you?

**Review by gaylem — CHANGES_REQUESTED** [review]
@derekeder Oh cool, thanks for doing that! Yeah I think there are just a few minor things I noticed:

1. You can probably remove the word "bash" from this sentence under the Important warning: "Please make sure the Docker Desktop application is running on your computer before you run the **bash** commands below."
2. Add a ## header between the "Environment setup" section and the Tests/Data processing section
3. There seems to be an extra space in this command between `chicago` and `bash`: `docker-compose run --rm electrify-chicago  bash run_all.sh`

Otherwise it's basically exactly what I did. I'll go ahead and close my PR and remove the branch I created.

**Comment by derekeder** [comment]
@gaylem thx - done!

**Review by gaylem — APPROVED** [review]

**Comment by vkoves** [comment]
@derekeder and @gaylem - the Pytest seems to be failing, it looks like you tweaked the test data and might need to tweak the tests

**Comment by derekeder** [comment]
@vkoves huh not sure how those extra rows were added. removed them and tests are passing now

**Comment by vkoves** [comment]
Gayle approved so I will merge

**Pull request merged**
