### PR TITLE
Keep Unreported Records For Python Grade Calculation

### PR DESCRIPTION
**Pull request by AlexanderTyan**
# Description

Change/rerun data preprocessing to keep unreporting records.

Relates to issue #129, because we need non-reporting data in the CSV to calculate reporting grades

# Testing Instructions

Please describe the tests/QA that you did to verify your changes. Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by vkoves** [comment]
@AlexanderTyan - it looks like you'll need to update the Python tests scripts, because now there's more records in the historical data than it expected!

**Comment by AlexanderTyan** [comment]
@vkoves i updated the test output csv according to the newly changed processing + updated expected answers in tests to match what's in there. the updates `test_output.csv` now has `'Not Submitted` rows, as wells as `'Submitted Data'` and `'Submitted'` rows.

**Comment by vkoves** [comment]
@AlexanderTyan - So I did find one issue, it looks like this change breaks the historical graphs, I think because now they are getting empty data 😭 

| Prod | Deploy Preview |
| --- | --- |
| Screenshot from 2024-10-29 21-27-26 | Screenshot from 2024-10-29 21-27-13 |

I think this can be fixed by making each graph filter out empty data - do you feel comfortable giving that a try, would you like me to try and fix it, or would you like to pair up on it next Chi Hack Night?

**Comment by AlexanderTyan** [comment]
@vkoves yeah, let's pair up next ChiHackNight!

**Review by vkoves — APPROVED** [review]
Looks great, awesome work!

**Pull request merged**
