### PR TITLE
98 search on map is broken

### LINKED ISSUE #98: Search on Map Is Broken
The Map page's utility has been reduced, because it can no longer find buildings around a specific building:

Screenshot from 2024-05-07 20-42-16

### PR DESCRIPTION
**Pull request by alexkcode**
# Description

Adds a check to map search to  make sure that lat long coordinates exist before doing the proximity calculation for the map building search feature.

Fixes #98 

# Testing Instructions

Checked a couple cases in the frontend, including Willis Tower (which was shown in the original issue). Should currently show all the buildings within the correct proximity of the filtered building. 

# Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by vkoves** [comment]
@alexkcode - I'm a little confused, I pulled your branch and still saw the issue, went to the map page and searched for the Willis Tower:

Screenshot from 2024-05-27 20-33-09

**Comment by alexkcode** [comment]
Crap made a stupid mistake. I think it should be fixed now but not entirely sure if what I'm what I'm doing is not an anti-pattern. Essentially I changed it so I'm just intermittently checking for `NaN`.  
Screenshot 2024-05-28 at 16-22-58 Map - Electrify Chicago

**Comment by alexkcode** [comment]
@vkoves please re-review when you get a chance!

**Review by vkoves — APPROVED** [review]
Looks great, confirmed the map search now works!

**Pull request merged**
