### PR TITLE
Add Historical Graph to Building Details Over Any Tracked Column

### LINKED ISSUE #4: Add Graph For Emissions Over Time On Building Details (Requires Integrating Full Data Source)
**Blocked by issue #73**, which will integrate the full data source.

Buildings like Keating may still be very high emitters, but they also have had emissions (and natural gas use) decrease over time, so to give a full picture it would be good to integrate historical data into a line graph showing the emissions over time.

This would also make it so that if we get, say, 2021 emissions data the old data would still be available and you could see the change YoY.

Since we have lots of fields you might want to see over time, we'd probably want to make the graph interactive, letting the user travel between different visualizations, but defaulting to a really useful one, like GHG intensity.

### PR DESCRIPTION
**Pull request by vkoves**
# Description

Adds a basic `BarGraph` component (powered by D3) and implements it on the building details page to show a switchable graph of a few of the historically tracked columns. Here's a demo with Marina Towers;

| Total Emissions | Electric Use |
| --- | --- |
| Screenshot from 2024-06-15 16-42-13 |Screenshot from 2024-06-15 16-41-54 |

Fixes #4 

# Testing Instructions

Please describe the tests/QA that you did to verify your changes. Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by alexkcode** [comment]
The pytest bug is a `pandas` issue related to this `numpy` issue: https://github.com/numpy/numpy/issues/26710

**Comment by alexkcode** [comment]
According this comment on that issue thread, as long as we're using `pandas == 2.2.2` and above we should be fine. But if we use any earlier version we must pin down a `numpy` version below `2.0.0`.

**Comment by alexkcode** [comment]
Getting an intermittent issue of D3 not installing with `docker compose up --build`, looking into it currently.

**Comment by vkoves** [comment]
@alexkcode I had that happen due to caching or having an existing build, I had to do a fresh Docker build to make sure it installs dependencies.

**Comment by vkoves** [comment]
@alexkcode - do you want to give this a proper final review?

**Review by alexkcode — APPROVED** [review]
Checked a couple different building sites, looks good!

**Pull request merged**
