### PR TITLE
Add Stat Spark Lines & Energy Mix Pie Chart 

### LINKED ISSUE #108: Add Smaller Graphs for Each Stat Card to Show Attributes Over Time
In PR #107 I added a way to see changes in building attributes, but it's not integrated into the stat cards and only lets you see one attribute at a time. Derek suggested smaller graphs (like stock ticker graphs, also known as spark lines) within each card.

We should work on this in Figma and come up with a design to make this all a little clearer, perhaps using Merchandise Mart and Keating as examples of large and small data sets.

### PR DESCRIPTION
**Pull request by vkoves**
# Description

Added a new `SparkLine` component that can render a basic line graph, and added a spark line for each of the main four stat tiles (after hiding site and source EUI), as well as a new `PieChart` that shows the mix of energy uses:

**Example from Merch Mart:**

Screenshot from 2024-08-27 23-46-57

Additionally, there's a hover behavior that shows all the underlying data points, and lets you hover over them to view exact values:

https://github.com/user-attachments/assets/98f0df48-dbb6-4a01-8ce1-32758b2d391f

Resolves #108, works on #110.

# Testing Instructions

Tested several buildings and confirmed the spark lines look good on desktop and mobile, with the min and max point values staying in the graph bounds. For example, here's Crown Hall (which bucks the trend of stats going down):

Screenshot from 2024-08-27 19-50-01

# Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by vkoves** [comment]
@derekeder - would you be down to tackle review?

**Comment by derekeder** [comment]
sure I can take a look

**Review by derekeder — APPROVED** [review]
overall, a great improvement. i think the pie charts are especially informative for quickly seeing the energy mix for a particular building. I clicked through about 30 different buildings and they all looked good to me.

one issue - the sparkline text is very tiny and almost impossible to read. I realize the units are whats taking the most space here. since the units are already stated in the large number in the same box, could we hide it from the sparkline and make the text bigger?

**Comment by vkoves** [comment]
@derekeder - updated! I'm a little torn, my chemistry teacher would always want a unit on a graph, but I think you're right that the unit is right there. We can always revise it and add it to a title:

| State | Image |
| --- | --- |
| Before | Screenshot from 2024-08-30 18-32-52 |
| After | Screenshot from 2024-08-30 18-33-00 |

**Comment by vkoves** [comment]
One thing to tackle later is buildings with data gaps don't render the spark line correctly, like Willis Tower:

Screenshot from 2024-08-30 19-18-40

**Comment by vkoves** [comment]
Final update, I added a note to Release Notes, going to merge it in!

Screenshot from 2024-08-30 20-32-54

**Comment by derekeder** [comment]
@vkoves nice! i think its a great improvement!

**Pull request merged**
